cc_test(
    name = "common_test",
    size = "small",
    srcs = [
        "common.cpp",
    ],
    deps = [
        "@gtest//:gtest_main",
        "//openconsult/src:common",
    ],
)

cc_test(
    name = "log_replay_test",
    size = "small",
    srcs = [
        "log_replay.cpp",
    ],
    deps = [
        "@gtest//:gtest_main",
        "//openconsult/src:log_replay",
    ],
)
