cc_test(
    name = "common_test",
    size = "small",
    srcs = ["common.cpp"],
    deps = [
        "@gtest//:gtest_main",
        "//openconsult/src:common",
    ],
)

cc_test(
    name = "consult_engine_parameters",
    size = "small",
    srcs = ["consult_engine_parameters.cpp"],
    deps = [
        "@gtest//:gtest_main",
        "//openconsult/src:consult_engine_parameters",
    ],
)

cc_test(
    name = "consult_fault_codes",
    size = "small",
    srcs = ["consult_fault_codes.cpp"],
    deps = [
        "@gtest//:gtest_main",
        "//openconsult/src:consult_fault_codes",
    ],
)

cc_test(
    name = "consult_interface",
    size = "small",
    srcs = ["consult_interface.cpp"],
    deps = [
        "@gtest//:gtest_main",
        "//openconsult/src:consult_interface",
    ],
)

cc_test(
    name = "log_recorder_test",
    size = "small",
    srcs = ["log_recorder.cpp"],
    deps = [
        "@gtest//:gtest_main",
        "//openconsult/src:log_recorder",
    ],
)

cc_test(
    name = "log_replay_test",
    size = "small",
    srcs = ["log_replay.cpp"],
    deps = [
        "@gtest//:gtest_main",
        "//openconsult/src:log_replay",
    ],
)
